//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLPractice.BillerInvoice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://efaktura.bg/soap/", ConfigurationName="BillerInvoice.BillerInvoicesWebServicePort")]
    public interface BillerInvoicesWebServicePort {
        
        // CODEGEN: Generating message contract since the operation getBillerInvoices is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="https://efaktura.bg/soap/BillerInvoicesWebService#getBillerInvoices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        XMLPractice.BillerInvoice.getBillerInvoicesResponse getBillerInvoices(XMLPractice.BillerInvoice.getBillerInvoices request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efaktura.bg/soap/BillerInvoicesWebService#getBillerInvoices", ReplyAction="*")]
        System.Threading.Tasks.Task<XMLPractice.BillerInvoice.getBillerInvoicesResponse> getBillerInvoicesAsync(XMLPractice.BillerInvoice.getBillerInvoices request);
        
        // CODEGEN: Generating message contract since the operation cancelInvoice is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="https://efaktura.bg/soap/BillerInvoicesWebService#cancelInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        XMLPractice.BillerInvoice.cancelInvoiceResponse cancelInvoice(XMLPractice.BillerInvoice.cancelInvoice request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efaktura.bg/soap/BillerInvoicesWebService#cancelInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<XMLPractice.BillerInvoice.cancelInvoiceResponse> cancelInvoiceAsync(XMLPractice.BillerInvoice.cancelInvoice request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public partial class BillerInvoicesRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] authorizationIdField;
        
        private byte[] authorizationKeyField;
        
        private LanguageType requestLanguageField;
        
        private bool requestLanguageFieldSpecified;
        
        private RequestFilterType filterField;
        
        private bool lastStatusField;
        
        private bool lastStatusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] authorizationId {
            get {
                return this.authorizationIdField;
            }
            set {
                this.authorizationIdField = value;
                this.RaisePropertyChanged("authorizationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] authorizationKey {
            get {
                return this.authorizationKeyField;
            }
            set {
                this.authorizationKeyField = value;
                this.RaisePropertyChanged("authorizationKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public LanguageType RequestLanguage {
            get {
                return this.requestLanguageField;
            }
            set {
                this.requestLanguageField = value;
                this.RaisePropertyChanged("RequestLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequestLanguageSpecified {
            get {
                return this.requestLanguageFieldSpecified;
            }
            set {
                this.requestLanguageFieldSpecified = value;
                this.RaisePropertyChanged("RequestLanguageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public RequestFilterType Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
                this.RaisePropertyChanged("Filter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool LastStatus {
            get {
                return this.lastStatusField;
            }
            set {
                this.lastStatusField = value;
                this.RaisePropertyChanged("LastStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastStatusSpecified {
            get {
                return this.lastStatusFieldSpecified;
            }
            set {
                this.lastStatusFieldSpecified = value;
                this.RaisePropertyChanged("LastStatusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public enum LanguageType {
        
        /// <remarks/>
        bul,
        
        /// <remarks/>
        eng,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public partial class RequestFilterType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActorID", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Email", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IdentificationNumber", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("InvoiceNumber", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("InvoiceStatuses", typeof(InvoiceStatusesType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("InvoiceTypes", typeof(InvoiceTypesType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("NewOnly", typeof(bool), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Period", typeof(FilterPeriodType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("VATIdentificationNumber", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public partial class InvoiceStatusesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InvoiceStatusType[] invoiceStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InvoiceStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public InvoiceStatusType[] InvoiceStatus {
            get {
                return this.invoiceStatusField;
            }
            set {
                this.invoiceStatusField = value;
                this.RaisePropertyChanged("InvoiceStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public partial class InvoiceStatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string statusNameField;
        
        private System.DateTime statusRegTimeStampField;
        
        private bool statusRegTimeStampFieldSpecified;
        
        private string statusActorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string StatusName {
            get {
                return this.statusNameField;
            }
            set {
                this.statusNameField = value;
                this.RaisePropertyChanged("StatusName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime StatusRegTimeStamp {
            get {
                return this.statusRegTimeStampField;
            }
            set {
                this.statusRegTimeStampField = value;
                this.RaisePropertyChanged("StatusRegTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusRegTimeStampSpecified {
            get {
                return this.statusRegTimeStampFieldSpecified;
            }
            set {
                this.statusRegTimeStampFieldSpecified = value;
                this.RaisePropertyChanged("StatusRegTimeStampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string StatusActor {
            get {
                return this.statusActorField;
            }
            set {
                this.statusActorField = value;
                this.RaisePropertyChanged("StatusActor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public partial class CancelInvoiceResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public partial class CancelInvoiceRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] authorizationIdField;
        
        private byte[] authorizationKeyField;
        
        private System.DateTime invoiceDateField;
        
        private string invoiceNumberField;
        
        private LanguageType requestLanguageField;
        
        private bool requestLanguageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] authorizationId {
            get {
                return this.authorizationIdField;
            }
            set {
                this.authorizationIdField = value;
                this.RaisePropertyChanged("authorizationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] authorizationKey {
            get {
                return this.authorizationKeyField;
            }
            set {
                this.authorizationKeyField = value;
                this.RaisePropertyChanged("authorizationKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime invoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
                this.RaisePropertyChanged("invoiceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string invoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
                this.RaisePropertyChanged("invoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public LanguageType requestLanguage {
            get {
                return this.requestLanguageField;
            }
            set {
                this.requestLanguageField = value;
                this.RaisePropertyChanged("requestLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestLanguageSpecified {
            get {
                return this.requestLanguageFieldSpecified;
            }
            set {
                this.requestLanguageFieldSpecified = value;
                this.RaisePropertyChanged("requestLanguageSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public partial class InvoiceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string invoiceNumberField;
        
        private System.DateTime invoiceDateField;
        
        private string uIDField;
        
        private InvoiceStatusType[] invoiceStatusesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
                this.RaisePropertyChanged("InvoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
                this.RaisePropertyChanged("InvoiceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
                this.RaisePropertyChanged("UID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("InvoiceStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public InvoiceStatusType[] InvoiceStatuses {
            get {
                return this.invoiceStatusesField;
            }
            set {
                this.invoiceStatusesField = value;
                this.RaisePropertyChanged("InvoiceStatuses");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public partial class RecipientType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vATIdentificationNumberField;
        
        private string identificationNumberField;
        
        private InvoiceType[] invoicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VATIdentificationNumber {
            get {
                return this.vATIdentificationNumberField;
            }
            set {
                this.vATIdentificationNumberField = value;
                this.RaisePropertyChanged("VATIdentificationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IdentificationNumber {
            get {
                return this.identificationNumberField;
            }
            set {
                this.identificationNumberField = value;
                this.RaisePropertyChanged("IdentificationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Invoice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public InvoiceType[] Invoices {
            get {
                return this.invoicesField;
            }
            set {
                this.invoicesField = value;
                this.RaisePropertyChanged("Invoices");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public partial class RecipientsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RecipientType[] recipientField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Recipient", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RecipientType[] Recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("Recipient");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public partial class BillerType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vATIdentificationNumberField;
        
        private string identificationNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VATIdentificationNumber {
            get {
                return this.vATIdentificationNumberField;
            }
            set {
                this.vATIdentificationNumberField = value;
                this.RaisePropertyChanged("VATIdentificationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IdentificationNumber {
            get {
                return this.identificationNumberField;
            }
            set {
                this.identificationNumberField = value;
                this.RaisePropertyChanged("IdentificationNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public partial class BillerInvoicesResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LanguageType responseLanguageField;
        
        private BillerType billerField;
        
        private RequestFilterType filterField;
        
        private bool lastStatusField;
        
        private bool lastStatusFieldSpecified;
        
        private RecipientsType recipientsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public LanguageType ResponseLanguage {
            get {
                return this.responseLanguageField;
            }
            set {
                this.responseLanguageField = value;
                this.RaisePropertyChanged("ResponseLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public BillerType Biller {
            get {
                return this.billerField;
            }
            set {
                this.billerField = value;
                this.RaisePropertyChanged("Biller");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public RequestFilterType Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
                this.RaisePropertyChanged("Filter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool LastStatus {
            get {
                return this.lastStatusField;
            }
            set {
                this.lastStatusField = value;
                this.RaisePropertyChanged("LastStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastStatusSpecified {
            get {
                return this.lastStatusFieldSpecified;
            }
            set {
                this.lastStatusFieldSpecified = value;
                this.RaisePropertyChanged("LastStatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public RecipientsType Recipients {
            get {
                return this.recipientsField;
            }
            set {
                this.recipientsField = value;
                this.RaisePropertyChanged("Recipients");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public partial class FilterPeriodType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PeriodTypeType periodTypeField;
        
        private System.DateTime periodFromField;
        
        private System.DateTime periodToField;
        
        private bool periodToFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PeriodTypeType PeriodType {
            get {
                return this.periodTypeField;
            }
            set {
                this.periodTypeField = value;
                this.RaisePropertyChanged("PeriodType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime PeriodFrom {
            get {
                return this.periodFromField;
            }
            set {
                this.periodFromField = value;
                this.RaisePropertyChanged("PeriodFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime PeriodTo {
            get {
                return this.periodToField;
            }
            set {
                this.periodToField = value;
                this.RaisePropertyChanged("PeriodTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PeriodToSpecified {
            get {
                return this.periodToFieldSpecified;
            }
            set {
                this.periodToFieldSpecified = value;
                this.RaisePropertyChanged("PeriodToSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public enum PeriodTypeType {
        
        /// <remarks/>
        InvoiceSendDate,
        
        /// <remarks/>
        InvoiceDate,
        
        /// <remarks/>
        InvoiceDueDate,
        
        /// <remarks/>
        InvoiceStatusChanged,
        
        /// <remarks/>
        SDXDate,
        
        /// <remarks/>
        SDXStatusChanged,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public partial class InvoiceTypesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InvoiceTypeType[] invoiceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InvoiceType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public InvoiceTypeType[] InvoiceType {
            get {
                return this.invoiceTypeField;
            }
            set {
                this.invoiceTypeField = value;
                this.RaisePropertyChanged("InvoiceType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public partial class InvoiceTypeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InvoiceTypeCodeType invoiceTypeCodeField;
        
        private string invoiceTypeTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public InvoiceTypeCodeType InvoiceTypeCode {
            get {
                return this.invoiceTypeCodeField;
            }
            set {
                this.invoiceTypeCodeField = value;
                this.RaisePropertyChanged("InvoiceTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string InvoiceTypeText {
            get {
                return this.invoiceTypeTextField;
            }
            set {
                this.invoiceTypeTextField = value;
                this.RaisePropertyChanged("InvoiceTypeText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/")]
    public enum InvoiceTypeCodeType {
        
        /// <remarks/>
        INV,
        
        /// <remarks/>
        KTN,
        
        /// <remarks/>
        DTN,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://efaktura.bg/soap/", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":ActorID")]
        ActorID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":Email")]
        Email,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":IdentificationNumber")]
        IdentificationNumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":InvoiceNumber")]
        InvoiceNumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":InvoiceStatuses")]
        InvoiceStatuses,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":InvoiceTypes")]
        InvoiceTypes,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":NewOnly")]
        NewOnly,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":Period")]
        Period,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":VATIdentificationNumber")]
        VATIdentificationNumber,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBillerInvoices {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://efaktura.bg/soap/", Order=0)]
        public XMLPractice.BillerInvoice.BillerInvoicesRequestType BillerInvoicesRequest;
        
        public getBillerInvoices() {
        }
        
        public getBillerInvoices(XMLPractice.BillerInvoice.BillerInvoicesRequestType BillerInvoicesRequest) {
            this.BillerInvoicesRequest = BillerInvoicesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBillerInvoicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://efaktura.bg/soap/", Order=0)]
        public XMLPractice.BillerInvoice.BillerInvoicesResponseType BillerInvoicesResponse;
        
        public getBillerInvoicesResponse() {
        }
        
        public getBillerInvoicesResponse(XMLPractice.BillerInvoice.BillerInvoicesResponseType BillerInvoicesResponse) {
            this.BillerInvoicesResponse = BillerInvoicesResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelInvoice {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://efaktura.bg/soap/", Order=0)]
        public XMLPractice.BillerInvoice.CancelInvoiceRequestType CancelInvoiceRequest;
        
        public cancelInvoice() {
        }
        
        public cancelInvoice(XMLPractice.BillerInvoice.CancelInvoiceRequestType CancelInvoiceRequest) {
            this.CancelInvoiceRequest = CancelInvoiceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelInvoiceResponse", Namespace="https://efaktura.bg/soap/", Order=0)]
        public XMLPractice.BillerInvoice.CancelInvoiceResponseType CancelInvoiceResponse1;
        
        public cancelInvoiceResponse() {
        }
        
        public cancelInvoiceResponse(XMLPractice.BillerInvoice.CancelInvoiceResponseType CancelInvoiceResponse1) {
            this.CancelInvoiceResponse1 = CancelInvoiceResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BillerInvoicesWebServicePortChannel : XMLPractice.BillerInvoice.BillerInvoicesWebServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BillerInvoicesWebServicePortClient : System.ServiceModel.ClientBase<XMLPractice.BillerInvoice.BillerInvoicesWebServicePort>, XMLPractice.BillerInvoice.BillerInvoicesWebServicePort {
        
        public BillerInvoicesWebServicePortClient() {
        }
        
        public BillerInvoicesWebServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BillerInvoicesWebServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillerInvoicesWebServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillerInvoicesWebServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XMLPractice.BillerInvoice.getBillerInvoicesResponse XMLPractice.BillerInvoice.BillerInvoicesWebServicePort.getBillerInvoices(XMLPractice.BillerInvoice.getBillerInvoices request) {
            return base.Channel.getBillerInvoices(request);
        }
        
        public XMLPractice.BillerInvoice.BillerInvoicesResponseType getBillerInvoices(XMLPractice.BillerInvoice.BillerInvoicesRequestType BillerInvoicesRequest) {
            XMLPractice.BillerInvoice.getBillerInvoices inValue = new XMLPractice.BillerInvoice.getBillerInvoices();
            inValue.BillerInvoicesRequest = BillerInvoicesRequest;
            XMLPractice.BillerInvoice.getBillerInvoicesResponse retVal = ((XMLPractice.BillerInvoice.BillerInvoicesWebServicePort)(this)).getBillerInvoices(inValue);
            return retVal.BillerInvoicesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XMLPractice.BillerInvoice.getBillerInvoicesResponse> XMLPractice.BillerInvoice.BillerInvoicesWebServicePort.getBillerInvoicesAsync(XMLPractice.BillerInvoice.getBillerInvoices request) {
            return base.Channel.getBillerInvoicesAsync(request);
        }
        
        public System.Threading.Tasks.Task<XMLPractice.BillerInvoice.getBillerInvoicesResponse> getBillerInvoicesAsync(XMLPractice.BillerInvoice.BillerInvoicesRequestType BillerInvoicesRequest) {
            XMLPractice.BillerInvoice.getBillerInvoices inValue = new XMLPractice.BillerInvoice.getBillerInvoices();
            inValue.BillerInvoicesRequest = BillerInvoicesRequest;
            return ((XMLPractice.BillerInvoice.BillerInvoicesWebServicePort)(this)).getBillerInvoicesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XMLPractice.BillerInvoice.cancelInvoiceResponse XMLPractice.BillerInvoice.BillerInvoicesWebServicePort.cancelInvoice(XMLPractice.BillerInvoice.cancelInvoice request) {
            return base.Channel.cancelInvoice(request);
        }
        
        public XMLPractice.BillerInvoice.CancelInvoiceResponseType cancelInvoice(XMLPractice.BillerInvoice.CancelInvoiceRequestType CancelInvoiceRequest) {
            XMLPractice.BillerInvoice.cancelInvoice inValue = new XMLPractice.BillerInvoice.cancelInvoice();
            inValue.CancelInvoiceRequest = CancelInvoiceRequest;
            XMLPractice.BillerInvoice.cancelInvoiceResponse retVal = ((XMLPractice.BillerInvoice.BillerInvoicesWebServicePort)(this)).cancelInvoice(inValue);
            return retVal.CancelInvoiceResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XMLPractice.BillerInvoice.cancelInvoiceResponse> XMLPractice.BillerInvoice.BillerInvoicesWebServicePort.cancelInvoiceAsync(XMLPractice.BillerInvoice.cancelInvoice request) {
            return base.Channel.cancelInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<XMLPractice.BillerInvoice.cancelInvoiceResponse> cancelInvoiceAsync(XMLPractice.BillerInvoice.CancelInvoiceRequestType CancelInvoiceRequest) {
            XMLPractice.BillerInvoice.cancelInvoice inValue = new XMLPractice.BillerInvoice.cancelInvoice();
            inValue.CancelInvoiceRequest = CancelInvoiceRequest;
            return ((XMLPractice.BillerInvoice.BillerInvoicesWebServicePort)(this)).cancelInvoiceAsync(inValue);
        }
    }
}
